package com.lunifera.graduate.ui.forms;

import com.lunifera.graduate.ui.fields.CountryField;
import com.lunifera.graduate.ui.fields.DivisionField;
import com.lunifera.graduate.ui.fields.TitleField;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class AuditorDetailView extends VerticalLayout {
	protected TabSheet masterTabSheet;
	protected TextField number;
	protected TextField lfp;
	protected TitleField title;
	protected TextField firstname;
	protected TextField firstname2;
	protected TextField nastname;
	protected TextField birthname;
	protected OptionGroup gender;
	protected TextField phone;
	protected TextField cellPhone;
	protected TextField mailAddress;
	protected TextField birthday;
	protected TextField birthplace;
	protected CountryField birthcountry;
	protected DivisionField division;
	protected TextField homeAddress_street;
	protected TextField homeAddress_postalcode;
	protected TextField homeAddress_city;
	protected TextField semesterAddress_street;
	protected TextField semesterAddress_postalcode;
	protected TextField semesterAddress_city;

	public AuditorDetailView() {
		Design.read(this);
	}
}
